version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    links: 
      - database
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=host.docker.internal
    extra_hosts:
      - host.docker.internal:host-gateway
volumes:
  data: